---
- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item.name }}"
    driver: "{{ item.driver | default('bridge') }}"
    internal: "{{ item.internal | default(false) }}"
    state: present
  loop:
    - name: "{{ proxy_network }}"
      driver: bridge
    - name: "{{ backend_network }}"
      driver: bridge
      internal: true
    - name: "{{ shared_network }}"
      driver: bridge
    - name: vpn-network
      driver: bridge
