---
- name: Create Homebox data volume
  community.docker.docker_volume:
    name: homebox-data

- name: Deploy Homebox
  community.docker.docker_container:
    name: homebox
    image: "{{ homebox_image }}"
    state: started
    restart_policy: "{{ restart_policy }}"
    networks:
      - name: "{{ proxy_network }}"
    ports:
      - "{{ homebox_external_port }}:{{ homebox_port }}"
    env:
      TZ: "{{ timezone }}"
      HBOX_LOG_LEVEL: "{{ homebox_log_level }}"
      HBOX_LOG_FORMAT: "{{ homebox_log_format }}"
      HBOX_WEB_MAX_UPLOAD_SIZE: "{{ homebox_max_upload_size }}"
      HBOX_OPTIONS_ALLOW_ANALYTICS: "{{ homebox_allow_analytics }}"
    volumes:
      - homebox-data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.homebox.rule: "Host(`{{ homebox_domain }}`)"
      traefik.http.routers.homebox.entrypoints: "websecure"
      traefik.http.routers.homebox.tls.certresolver: "letsencrypt"
      traefik.http.services.homebox.loadbalancer.server.port: "{{ homebox_port }}"
    log_driver: "{{ logging_driver }}"
    log_options:
      max-size: "{{ logging_max_size }}"
      max-file: "{{ logging_max_file }}"
