---
- name: Create content-management base directory
  file:
    path: "{{ docker_base_path }}/{{ stack_name }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'

- name: Deploy compose file
  copy:
    src: compose.yaml
    dest: "{{ docker_base_path }}/{{ stack_name }}/compose.yaml"
    owner: "{{ ansible_user }}"
    mode: '0644'

- name: Create content-management config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - "{{ config_base }}"

- name: Deploy Immich
  import_tasks: immich.yml
  tags: immich

- name: Deploy Papra
  import_tasks: papra.yml
  tags: papra

- name: Deploy SongKong
  import_tasks: songkong.yml
  tags: songkong

- name: Deploy Homebox
  import_tasks: homebox.yml
  tags: homebox
