---
- name: Create SongKong volume
  community.docker.docker_volume:
    name: songkong-config

- name: Deploy SongKong
  community.docker.docker_container:
    name: songkong
    image: "{{ songkong_image }}"
    state: started
    restart_policy: "{{ restart_policy }}"
    networks:
      - name: "{{ shared_network }}"
    ports:
      - "{{ songkong_port }}:4567"
    env:
      TZ: "{{ timezone }}"
    volumes:
      - songkong-config:/songkong
      - music:/music
    log_driver: "{{ logging_driver }}"
    log_options:
      max-size: "{{ logging_max_size }}"
      max-file: "{{ logging_max_file }}"
