---
- name: Deploy Jellyseerr
  community.docker.docker_container:
    name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    state: started
    restart_policy: "{{ restart_policy }}"
    networks:
      - name: shared-network
    ports:
      - "5055:5055"
    env:
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_base }}/jellyseerr:/app/config"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5055/api/v1/status"]
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    log_driver: "{{ logging_driver }}"
    log_options:
      max-size: "{{ logging_max_size }}"
      max-file: "{{ logging_max_file }}"
